# docker-compose.yml
version: '3.8'

services:
  api-gateway:
    build: ./api_gateway
    ports:
      - "${API_GATEWAY_PORT}:8000"
    environment:
      - AGENT_SERVICE_URL=http://agent-service:8000
      - RAG_SERVICE_URL=http://rag-service:8001
      - RESERVATION_SERVICE_URL=http://reservation-service:8002
      - LOG_LEVEL=${LOG_LEVEL}
    depends_on:
      - agent-service
    restart: unless-stopped
    networks:
      - convagent-network

  agent-service:
    build: ./agent_service
    environment:
      - RAG_SERVICE_URL=http://rag-service:8001
      - RESERVATION_SERVICE_URL=http://reservation-service:8002
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LOG_LEVEL=${LOG_LEVEL}
    depends_on:
      - rag-service
      - reservation-service
    restart: unless-stopped
    networks:
      - convagent-network

  rag-service:
    build: ./rag_service
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - VECTORSTORE_PATH=${VECTORSTORE_PATH}
      - LOG_LEVEL=${LOG_LEVEL}
    volumes:
      - rag-data:/app/vectorstore
    restart: unless-stopped
    networks:
      - convagent-network

  reservation-service:
    build: ./reservation_service
    environment:
      - DB_PATH=${DB_PATH}
      - LOG_LEVEL=${LOG_LEVEL}
    volumes:
      - reservation-data:/data
    restart: unless-stopped
    networks:
      - convagent-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - convagent-network

volumes:
  rag-data:
  reservation-data:
  redis-data:

networks:
  convagent-network:
    driver: bridge