apiVersion: v1
kind: ConfigMap
metadata:
  name: schedule-config
data:
  PG_HOST: "localhost"  # Change to your PostgreSQL host
  PG_PORT: "5432"
  PG_DB: "your_db"
  PG_USER: "postgres"
  MODEL_NAME: "gpt-4o"
  TEMPERATURE: "0"
  # Add more config if needed

---
apiVersion: v1
kind: Secret
metadata:
  name: schedule-secret
type: Opaque
stringData:
  OPENAI_API_KEY: ""
  PG_PASSWORD: "mlcohort@4"
  

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: schedule-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schedule-service
  template:
    metadata:
      labels:
        app: schedule-service
    spec:
      containers:
        - name: schedule-service
          image: schedule-service:latest    # Use the correct local image tag
          imagePullPolicy: Never
          ports:
            - containerPort: 8001           # Your FastAPI app port
          env:
            - name: PG_HOST
              valueFrom:
                configMapKeyRef:
                  name: schedule-config
                  key: PG_HOST
            - name: PG_PORT
              valueFrom:
                configMapKeyRef:
                  name: schedule-config
                  key: PG_PORT
            - name: PG_DB
              valueFrom:
                configMapKeyRef:
                  name: schedule-config
                  key: PG_DB
            - name: PG_USER
              valueFrom:
                configMapKeyRef:
                  name: schedule-config
                  key: PG_USER
            - name: MODEL_NAME
              valueFrom:
                configMapKeyRef:
                  name: schedule-config
                  key: MODEL_NAME
            - name: TEMPERATURE
              valueFrom:
                configMapKeyRef:
                  name: schedule-config
                  key: TEMPERATURE
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: schedule-secret
                  key: PG_PASSWORD
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: schedule-secret
                  key: OPENAI_API_KEY

---
apiVersion: v1
kind: Service
metadata:
  name: schedule-service
spec:
  selector:
    app: schedule-service
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  type: ClusterIP
