# .github/workflows/cd.yaml
name: CD - Agent Service

# Only trigger, when the build workflow succeeded i.e. CI Pipeline
on:
  push:
    branches: [ feature/react_agent_rh ]
  # workflow_run:
  #   workflows: ["CI - Agent Service"]
  #   types:
  #     - completed

jobs:
  deploy-chroma-service:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: RAG_React_tool/microservices/chroma    

    steps:
      - name: Checkout code
        uses: actions/checkout@v3    
      - name: Deploy pod
        run: kubectl apply -f chroma-deployment.yaml
