# .github/workflows/ci.yml
name: CI - Agent Service

on:
  push:
    branches: [ feature/react_agent_rh ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-container-agent-service:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: RAG_React_tool/microservices/agent_service

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: AGENT SERVICE Build Docker image
        run: |
          docker build -t agent-service:latest .
        

      - name: AGENT SERVICE Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_PASS_TOKEN }}

      - name: AGENT SERVICE Push image to DockerHub
        run: |
          docker tag agent-service:latest ravikumarbgdocker/agent-service:latest
          docker push ravikumarbgdocker/agent-service:
